### ISSUE TITLE
?

### ISSUE THREAD

**Issue by sad2project** [j-roskopf/ModuleMakerPlugin#23]
We're going to need some examples that explain what exactly this DOES. What does it mean when it says that it allows us to make modules without copying and pasting? Does it just make a new package with the module name and 3 kotlin files under it named "public", "impl", and "impl-wiring" (plus some gradle stuff)?

**Comment by j-roskopf** [comment]
Hey!

I have a video demoing off the project included on the Jetbrains page for it (https://plugins.jetbrains.com/plugin/21724-module-maker) which I will add to the readme on the project as well for better discoverability

https://www.youtube.com/watch?v=ZtXCxBuiQNk

But yeah that's the general idea. When you create a new module, it will create that module on the file system and it will add it to your settings.gradle(.kts) file and trigger a sync in AS / Intellij.

I hope that answers your questions! If there is any other type of documentation you're interested in seeing, I'd be happy to add it.
