### ISSUE TITLE
Allow configuration of three module folder names

### ISSUE THREAD

**Issue by igor-budi** [j-roskopf/ModuleMakerPlugin#31]
Having "hard coded" `api`, `glue` and `impl` folders for the three module structures requires manual rename in our project, where we use `di` instead of glue.

Making these names configurable makes it better adoptable in existing projects that already use this structure of modules

**Comment by j-roskopf** [comment]
hey! that totally makes sense. I'll add it for the next release

**Comment by j-roskopf** [comment]
<img width="826" alt="Screenshot 2023-07-06 at 2 17 33 PM" src="https://github.com/j-roskopf/ModuleMakerPlugin/assets/7951665/8eec8c2d-c983-474f-b8b1-f309d1979a83">
<img width="339" alt="Screenshot 2023-07-06 at 2 18 02 PM" src="https://github.com/j-roskopf/ModuleMakerPlugin/assets/7951665/96ad440e-13e4-43cc-86af-e8d59ce9aefd">
<img width="355" alt="Screenshot 2023-07-06 at 2 18 31 PM" src="https://github.com/j-roskopf/ModuleMakerPlugin/assets/7951665/a85b097d-115d-462d-8cfb-e03cb4d310d7">

**Comment by j-roskopf** [comment]
version 1.0.10 has been uploaded for review with this change. thanks again for raising the issue!

**Comment by igor-budi** [comment]
@j-roskopf thanks!
