### ISSUE TITLE
Module creation causes an error without logs

### ISSUE THREAD

**Issue by igor-budi** [j-roskopf/ModuleMakerPlugin#32]
When I try to create a module in my project, after clicking "create" there is a popup with an "Error" text in it.
Dismissing this popup will present another one with "Success".

The created modules are found in the repo, however `settings.gradle` file is not updated.

I wonder if the first error is related to the settings file.
In any case, logs in any form would be very useful, like a log file that would be generated somewhere.

**Comment by j-roskopf** [comment]
hey! thanks for raising the issue. I agree it was pretty short sighted to not have any logs available. is there a minimum settings.gradle gist you could share with me to repro? totally understandable if not. either way, with the next update i'll add some better telemetry options

**Comment by j-roskopf** [comment]
Looking at the code a little closer, I'm guessing the part that is failing is the area where Module Maker looks to find the first included module in your settings.gradle file. can you give me an example of how you are including modules within your project?

**Comment by igor-budi** [comment]
This is the main `settings.gradle` file in the project.
After this section, there is a long list of dependencies in a regular structure (list of `include ":dependency:bla"`)

![image](https://github.com/j-roskopf/ModuleMakerPlugin/assets/59958761/40de5d67-7c87-4e2a-8314-81a1a06b859e)

**Comment by j-roskopf** [comment]
A fix for this should be released in version 1.0.11

Thank you!
