### ISSUE TITLE
[Suggestion] Name gradle file additional options

### ISSUE THREAD

**Issue by igor-budi** [j-roskopf/ModuleMakerPlugin#43]
The option to name gradle file differently require additional step of including the new module differently in `settings.gradle`

As the actual implementation of supporting build files with different name can vary between projects and their maintainers, it will eventually come to a function call in the settings file.

So basically what I am suggesting here is an additional option to name the `include ':my-module` function with a different configurable name like `includeModule ':my-module`

**Comment by j-roskopf** [comment]
Totally makes sense! Internally on a lot of my personal and work projects, we always use a custom function for including modules which I've just always called 'includeProject' - I already have a TODO in the code (https://github.com/j-roskopf/ModuleMakerPlugin/blob/f142b379cfaf9a2abe4e5b519460adf8727f0e5c/src/main/kotlin/com/joetr/modulemaker/file/FileWriter.kt#L292) for this functionality. I think adding a custom settings field for specifying a list of 'include' keywords is probably how I'll tackle it
