### ISSUE TITLE
Support large project structure

### ISSUE THREAD

**Issue by igor-budi** [j-roskopf/ModuleMakerPlugin#44]
Gradle presents this structure as an option for structuring large projects
https://docs.gradle.org/current/userguide/structuring_software_products.html

Implementing this leads to multiple `settings.gradle` files in the project, where the root project has its own `settings.gradle` that links the projects together.

Currently, the plugin fails to add the changes to the settings.gradle file when attempting to add the new include module entries

**Comment by igor-budi** [comment]
I've made a small repo that is build in that way

https://github.com/igor-budi/codebase-template/

**Comment by j-roskopf** [comment]
Ohhh, I'll definitely take a look to see how feasible it will be!

**Comment by j-roskopf** [comment]
@igor-budi what is the logic you'd expect to see in this scenario? should Module Maker search for the first settings.gradle.kts file it finds going upwards from the selected root? Or are you looking for the ability to specify the specific settings.gradle.kts file in the UI?

**Comment by igor-budi** [comment]
I think it should always check the root itself and upwards 
You can try adding a module to the `DemoApp` in the sample project to see what is the problem

**Comment by j-roskopf** [comment]
makes sense! Put up a PR to address this issue and released it in version 1.0.13
